import type { StoryProject } from "./types";

export const sampleProject: StoryProject = {
  schemaVersion: 1,
  projectId: "neoarchive-sample",
  title: "新的约定",
  entrySceneId: "scene-001",
  createdAt: "2026-08-13T00:00:00Z",
  updatedAt: "2026-08-13T00:00:00Z",
  chapters: [
    {
      id: "chapter-001",
      title: "Chapter 01",
      scenes: [
        {
          id: "scene-001",
          title: "清晨的教室",
          kind: "dialogue",
          nextSceneId: "scene-002",
          cues: [
            {
              id: "cue-audio-001",
              type: "audio.play",
              atMs: 0,
              assetRef: "audio/cc0/tozan-background-music-1.ogg",
              channel: "bgm",
              loop: true,
              volume: 0.45,
            },
            {
              id: "cue-bg-001",
              type: "background.set",
              atMs: 0,
              assetRef: "background/classroom",
              transitionMs: 400,
            },
            {
              id: "cue-character-001",
              type: "character.enter",
              atMs: 0,
              characterRef: "character/png-elf-standee",
              animation: "idle",
              transform: { x: 0.5, y: 0.72, scale: 1.05 },
            },
            {
              id: "cue-dialogue-001",
              type: "dialogue.show",
              atMs: 450,
              speaker: "Sakurako",
              subtitle: "Trinity General School",
              text: "老师，今天也请允许我陪你一起完成这份档案。",
              typingCps: 36,
              waitForAdvance: true,
            },
            {
              id: "cue-dialogue-001b",
              type: "dialogue.show",
              atMs: 900,
              speaker: "老师",
              subtitle: "Schale",
              text: "当然。先从这一幕开始，把每一句话和每一个动作都安排好。",
              typingCps: 36,
              waitForAdvance: true,
            },
          ],
        },
        {
          id: "scene-002",
          title: "窗边的光",
          kind: "direction",
          nextSceneId: "scene-003",
          cues: [
            {
              id: "cue-transition-002",
              type: "transition.play",
              atMs: 0,
              preset: "archive-shutter",
              durationMs: 1100,
              holdMs: 120,
              intensity: 1,
            },
            {
              id: "cue-bg-002",
              type: "background.set",
              atMs: 0,
              assetRef: "background/rooftop",
              transitionMs: 500,
            },
            {
              id: "cue-character-002",
              type: "character.enter",
              atMs: 100,
              characterRef: "character/sakurako-idol",
              animation: "Idle_01",
              transform: { x: 0.52, y: 0.8, scale: 1.65 },
            },
            {
              id: "cue-dialogue-002",
              type: "dialogue.show",
              atMs: 600,
              speaker: "老师",
              subtitle: "Schale",
              text: "当然。我们先把故事的骨架搭好，再一点点填入细节。",
              typingCps: 36,
              waitForAdvance: true,
            },
            {
              id: "cue-dialogue-002b",
              type: "dialogue.show",
              atMs: 1100,
              speaker: "Sakurako",
              subtitle: "Trinity General School",
              text: "我会记住的。剧本、舞台和最后的播放，都使用同一份故事。",
              typingCps: 36,
              waitForAdvance: true,
            },
          ],
        },
        {
          id: "scene-003",
          title: "新的约定",
          kind: "choice",
          cues: [
            {
              id: "cue-transition-003",
              type: "transition.play",
              atMs: 0,
              preset: "halo-iris",
              durationMs: 950,
              holdMs: 80,
              intensity: 1,
            },
            {
              id: "cue-bg-003",
              type: "background.set",
              atMs: 0,
              assetRef: "background/park",
              transitionMs: 500,
            },
            {
              id: "cue-character-003",
              type: "character.enter",
              atMs: 100,
              characterRef: "character/sakurako-idol",
              animation: "Idle_01",
              transform: { x: 0.5, y: 0.8, scale: 1.65 },
            },
            {
              id: "cue-dialogue-003",
              type: "dialogue.show",
              atMs: 500,
              speaker: "Sakurako",
              subtitle: "Trinity General School",
              text: "那么，我们就从这一页正式开始吧。",
              typingCps: 36,
              waitForAdvance: true,
            },
            {
              id: "cue-choice-001",
              type: "choice.show",
              atMs: 900,
              prompt: "保存这份约定吗？",
              options: [
                { id: "choice-save", label: "保存约定" },
                { id: "choice-review", label: "再看一遍", targetSceneId: "scene-001" },
              ],
            },
          ],
        },
      ],
    },
  ],
};
